### ISSUE TITLE
gzip issues

### ISSUE THREAD

**Issue by marknadig** [attachmentsme/ruby-box#82]
Anyone else running into issues w/ gzipped responses? Testing this out locally with Ruby  2.0.0p247 and is abending on refresh_token call (via oauth2 gem). c/f https://github.com/intridea/oauth2/pull/159

However, seems this should be handled further up (Net::HTTP, Faraday). 

```
> 2.0.0-p247 :016 > client.root_folder
OAuth2::Error: <??
?@E?e?.D?ҝV*??c`????_??3Z??M-Z?????"yY??po?#6qՠ?b?L???}?H-\?r?hz%
??!????9S?L?r?Jz?}?|Q-i??zH???1?5h?ЊE?DF?3?yP??as?,? 51ѕq???pB#)??BD???b6L
                                                                          ??r??????aa??
    from /Users/marknadig/.rvm/gems/ruby-2.0.0-p247@kona/gems/oauth2-0.9.3/lib/oauth2/client.rb:137:in `get_token'
    from /Users/marknadig/.rvm/gems/ruby-2.0.0-p247@kona/gems/oauth2-0.9.3/lib/oauth2/access_token.rb:86:in `refresh!'
    from /Users/marknadig/.rvm/gems/ruby-2.0.0-p247@kona/gems/ruby-box-1.13.0/lib/ruby-box/session.rb:38:in `refresh_token'
    from /Users/marknadig/.rvm/gems/ruby-2.0.0-p247@kona/gems/ruby-box-1.13.0/lib/ruby-box/session.rb:81:in `request'
```

Similar issue here w/ oauth gem after updating to Ruby 2
http://www.extendi.it/blog/2013/12/02/6-oauth-gem-and-ruby-2-0-0

**Comment by bcoe** [comment]
Looks like it's an issue in the intridea/oauth2 library -- I can see you already made a comment on this thread:

https://github.com/intridea/oauth2/pull/159

Let me know if you any headway, and we can update ruby-box's dependency.

**Comment by marknadig** [comment]
Yeah, for now I went with the solution from datacompboy here http://stackoverflow.com/questions/13397119/ruby-nethttp-not-decoding-gzip defining  a HTTPResponseDecodeContentOverride

**Comment by bcoe** [comment]
It would be good to get this patch into RubyBox. Will any operation cause problems in  Ruby 2.0.0p247?

**Comment by marknadig** [comment]
I'm pretty sure I ran into this with all operations - since response is zipped, if falls down pretty quickly.

Note: I had to add a guard in mine to check for bytesize

``` ruby
if RUBY_VERSION > "2.0."
  module HTTPResponseDecodeContentOverride
    def initialize(h,c,m)
      super(h,c,m)
      @decode_content = true
    end
    def body
      res = super
      if self['content-length'] and res and res.respond_to? :bytesize
        self['content-length']= res.bytesize
      end
      res
    end
  end
  module Net
    class HTTPResponse
      prepend HTTPResponseDecodeContentOverride
    end
  end
end
```

Still feels a bit hacky to me... hoping this gets dealt with over on the oauth side and this is just a temp fix.

**Comment by bcoe** [comment]
I just ran the integration test suite with ruby-2.0.0-p247 and ruby-2.0.0-p353 can't seem to recreate this issue, I wonder what's different with my configuration.
